# Generated by Django 4.1 on 2023-09-16 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='default_book', max_length=255, verbose_name='image'),
        ),
    ]
