# Generated by Django 4.1 on 2023-09-16 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='./images/default_book.webp', max_length=255, verbose_name='image'),
        ),
    ]
