# Generated by Django 4.1 on 2023-09-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
