# Generated by Django 4.1 on 2023-10-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
